### PR TITLE
add option for default tags

### PR DESCRIPTION
**Pull request by thomasrebele**
I wanted to use taskwarrior also to organize tasks related to my job. I decided to put work-related and private tasks in one taskwarrior "session". My idea: use tags for hiding / showing the relevant tasks in vit.

scenario:
1. execute `vit --default-tags '+job'`
2. vit only shows tasks with tag `job`
3. add tasks. The new tasks will have the `job` tag

### CODE REVIEW

**Comment by thomasrebele** [comment]
related issue: #145

**Comment by scottkosty** [comment]
@thomasrebele thanks for your work on this! I don't have time to look at it now, but I made a note to look at it when I have time (this might not be for a while though).

**Comment by noahfrederick** [comment]
@thomasrebele Maybe I'm misunderstanding the feature, but don't [Contexts](https://taskwarrior.org/docs/context.html) already cover (most of) your use case? E.g., `task context job && vit`.

Using contexts has advantages over this approach:

- Not exclusive to a specific UI such as vit
- More flexible (you can filter by tags, project, or any other criteria)

That being said, I'm looking forward to [better context support](https://github.com/scottkosty/vit/issues/136) in vit.

I realize that contexts don't really cover item 3 above, which is something I would find useful as well, but I'd much rather see it added upstream rather than to vit, and to be generalized to any properties, not just tags.

**Comment by thomasrebele** [comment]
Indeed, the context feature is almost what I want. However, as @noahfrederick mentioned, it does not support setting tags automatically on newly created tasks. It would be nice to add such a feature to taskwarrior directly.

**Comment by thomasrebele** [comment]
Revisiting this issue again: The taskwarrior hooks API allows to modify a task before adding it. This allows to set the tags based on the context. I implemented a script that analyzes the context definition and adds the tags.

You can find the script [here](https://github.com/thomasrebele/dotfiles/blob/master/config/terminal/taskwarrior.install/.task.dir/hooks.dir/on-add-set-context.symlink). Put it in the hooks dir (normally it's ~/.task/hooks), and use the context feature mentioned by @noahfrederick.

**Comment by thehunmonkgroup** [comment]
@thomasrebele, looks like your hook script addresses the issue, so no need to reopen this, correct?

Also, I took a quick look at your script, you might change the line that finds the context to something more like:

```sh
task _show | grep "context=" | sed "s/context=//"
```

```task _show``` is nice in that it gives you much more machine readable output.

Also, rewriting JSON in Bash? That's bold ;) I think I would have gone with Python.

**Comment by thomasrebele** [comment]
Thanks for the tip with `task _show`. I've changed my script accordingly.

I made the script work with sh (probably also POSIX compliant). That should make it future-proof ;)

**Pull request closed without merging**
