### PR TITLE
Refresh every 30 minutes

### PR DESCRIPTION
**Pull request by jspricke**

### CODE REVIEW

**Comment by jspricke** [comment]
Patch from #69.

**Comment by scottkosty** [comment]
See also #169.

**Comment by thehunmonkgroup** [comment]
1.3 branch is no longer receiving non-security updates.

**Comment by thehunmonkgroup** [comment]
Can be accomplished with the auto-refresh tools: https://github.com/vit-project/vit/blob/2.x/CUSTOMIZE.md#auto-refreshing-vits-interface

**Pull request closed without merging**
